- name: Install Chrome
  homebrew_cask:
    name: google-chrome
    state: present

- name: Check if Google Chrome is the default browser
  command: defaultbrowser
  register: is_google_chrome_the_default_browser

- name: Make Google Chrome the default browser
  command: defaultbrowser chrome
  when: "is_google_chrome_the_default_browser.stdout.find('* chrome') == -1"