---
- name: Install zsh
  homebrew: name=zsh state=latest
  register: installation

- name: Make zsh the default shell
  shell: chsh -s $(which zsh)
  when: installation|success

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src="zshrc"
    dest=~/.zshrc
  when: cloning|success
  sudo: no